<a href="https://colab.research.google.com/github/lol-mann/data_science_course/blob/master/numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy

arange

In [2]:
import numpy as np

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
A = np.arange(25)

In [5]:
A.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [14]:
Z = np.arange(11)
selected = Z[(3 < Z) & (Z <= 8)]
print(Z)
print(selected)

[ 0  1  2  3  4  5  6  7  8  9 10]
[4 5 6 7 8]


inplace condition

In [15]:
Z[(3 < Z) & (Z <= 8)] *2
print(Z)

[ 0  1  2  3  4  5  6  7  8  9 10]


find common values between two arrays

In [21]:
Z1 = np.array([0, 1, 0, 8, 4, 1, 9, 3, 9, 4])
Z2 = np.array([2, 5, 9, 9, 1, 9, 9, 0, 6, 6])
print(np.intersect1d(Z1,Z2))

[0 1 9]


# exercises

##  Print the numpy version and the configuration.

## Create a null vector of size 25.

null vector/array is an vector/array with all elements as zeros

eg: [0,0,0,0]

## How to find the memory size of any array.

## Create a null vector of size 10 but the ninth value which is 1.

## Reverse an array

## Create a 6x6 identity matrix.

## Create a 3x3x3 array with random values.

## Create a 2d array with 1 on the border and 0 inside.

expected output

    [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
    [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
    [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
    [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
    [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
    [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
    [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
    [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
    [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
    [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

## What is the result of the following expression?


    print(0 * np.nan)
    print(np.nan == np.nan)
    print(np.inf > np.nan)
    print(np.nan - np.nan)
    print(np.nan in set([np.nan]))
    print(0.3 == 3 * 0.1)

## Multiply a 5x3 matrix by a 3x2 matrix (dot product)



In [0]:
A = np.ones((5,3))
B = np.ones((3,2))


why the following code has two different answers

In [8]:
print(sum(range(5),-1))
from numpy import *
print(np.sum(range(5),-1))

9
10


## How to sort an array by the nth column?

In [0]:
Z = np.random.randint(0,10,(3,3))